language: ruby
rvm:
  - '2.1'
before_install:
  - sudo add-apt-repository ppa:lyrasis/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libjpeg-dev libpng-dev libtiff-dev libwebp-dev
install:
  # Install Jekyll and dependencies
  - bundle install
script: bundle exec jekyll build && bundle exec s3_website push
