language: ruby
rvm: 2.1
cache: bundler
sudo: false
bundler_args: --without development --deployment
before_install:
  - wget http://downloads.webmproject.org/releases/webp/libwebp-0.4.2.tar.gz
  - tar xvzf libwebp-0.4.2.tar.gz
  - cd libwebp-0.4.2
  - ./configure --prefix=/home/travis/opt
  - make && make install
  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:/home/travis/opt/lib
install:
  # Install Jekyll and dependencies
  - bundle install --path .bundle
script: bundle exec jekyll build #&& bundle exec s3_website push
